export type RulesQuestion = {
  id: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
};

export type BackupScenario = {
  id: string;
  label: string;
  runners: { first: boolean; second: boolean; third: boolean };
  // ballZone = where the ball is / where the action originates
  ballZone: 'LF' | 'CF' | 'RF' | 'P' | '1B' | '2B' | 'SS' | '3B' | 'C';
  question: string;
  // targetZone = the position circle the player should tap
  targetZone: 'LF' | 'CF' | 'RF' | 'P' | '1B' | '2B' | 'SS' | '3B' | 'C';
  explanation: string;
  // Does the ball actually travel from ballZone to targetZone (a real throw/relay
  // the target receives), or is targetZone a pure backup/standby/mental-check role
  // that never touches the ball in this depicted moment? Defaults to true (relay
  // shown as a second ball hop after the answer reveal). Set false for backup-only
  // positions so we don't animate a throw that never happens.
  ballReachesTarget?: boolean;
};

// ─── RULES QUIZ ─────────────────────────────────────────────────────────────
// 9U Kid Pitch, Open Bases (leadoffs + full stealing)

export const RULES_QUESTIONS: RulesQuestion[] = [
  // ── Basics ──
  {
    id: 'r1',
    question: 'How many strikes does it take to strike out?',
    options: ['2 strikes', '3 strikes', '4 strikes', '1 strike'],
    correct: 1,
    explanation: '3 strikes and you\'re out! After 2 strikes the batter has one more chance before the at-bat is over.',
  },
  {
    id: 'r2',
    question: 'How many balls does a batter need to earn a walk?',
    options: ['3 balls', '2 balls', '5 balls', '4 balls'],
    correct: 3,
    explanation: '4 balls = walk! A ball is a pitch outside the strike zone the batter doesn\'t swing at. Four of those and the batter trots to first.',
  },
  {
    id: 'r3',
    question: 'How many outs end a team\'s half of the inning?',
    options: ['2 outs', '4 outs', '3 outs', '1 out'],
    correct: 2,
    explanation: '3 outs end the half inning, then the other team bats!',
  },
  {
    id: 'r4',
    question: 'How many players are on the field for the defense at one time?',
    options: ['7 players', '8 players', '10 players', '9 players'],
    correct: 3,
    explanation: '9 players: pitcher, catcher, four infielders (1B, 2B, 3B, SS), and three outfielders (LF, CF, RF).',
  },
  {
    id: 'r5',
    question: 'If a batter hits the ball over the outfield fence in FAIR territory, what is it?',
    options: ['A double', 'A ground rule double', 'A home run', 'A foul ball'],
    correct: 2,
    explanation: 'HOME RUN! The batter rounds all the bases and scores, along with any runners already on base.',
  },
  {
    id: 'r6',
    question: 'What is a "force out"?',
    options: [
      'When a fielder throws the ball very hard',
      'When a runner steals a base',
      'When a runner HAS to advance because the batter put the ball in play',
      'When a pitcher throws 4 balls in a row',
    ],
    correct: 2,
    explanation: 'A force out: with a runner on 1st and the batter getting a hit, that runner is FORCED to 2nd. The fielder just needs to touch 2nd with the ball — no tag needed!',
  },
  {
    id: 'r7',
    question: 'What happens when a fielder catches a fly ball before it hits the ground?',
    options: ['It\'s a hit', 'The batter is out', 'The batter gets an extra base', 'It\'s a foul ball'],
    correct: 1,
    explanation: 'Batter is out! Any fly ball caught before touching the ground is an out — even in foul territory.',
  },
  {
    id: 'r8',
    question: 'What does "RBI" stand for?',
    options: ['Runner Brought In', 'Really Big Inning', 'Run Batted In', 'Runner Beats Infield'],
    correct: 2,
    explanation: 'RBI = Run Batted In. You earn an RBI when your hit (or walk) causes a runner to score.',
  },
  {
    id: 'r9',
    question: 'How many bases must you touch to score a run?',
    options: ['Just home plate', '2 bases', '3 bases', 'All 4 — 1st, 2nd, 3rd, then home'],
    correct: 3,
    explanation: 'Touch \'em all! Miss any base and you can be called out.',
  },
  {
    id: 'r10',
    question: 'What is a "bunt"?',
    options: [
      'When a batter taps the ball softly on purpose',
      'A ball that hits the batter',
      'A really hard swing that misses',
      'A ball that bounces over the fence',
    ],
    correct: 0,
    explanation: 'A bunt is when the batter holds the bat still and taps the ball softly! Used to move runners or surprise the defense.',
  },
  {
    id: 'r11',
    question: 'What position wears the most protective gear?',
    options: ['Pitcher', 'Shortstop', 'Catcher', 'Center fielder'],
    correct: 2,
    explanation: 'The catcher wears a helmet, mask, chest protector, and shin guards. Every pitch, every throw — they take a beating!',
  },
  {
    id: 'r12',
    question: 'In the outfield, which player is in the MIDDLE?',
    options: ['Left fielder', 'Right fielder', 'Shortstop', 'Center fielder'],
    correct: 3,
    explanation: 'Center fielder (CF)! They cover the most ground and usually call off the other outfielders on fly balls.',
  },
  {
    id: 'r13',
    question: 'What is a "double play"?',
    options: [
      'When a batter gets two hits in a row',
      'Two outs made on the same play',
      'A play that scores two runs',
      'When two fielders touch the ball at once',
    ],
    correct: 1,
    explanation: 'Double play = 2 outs on 1 play! Most common: ground ball → throw to 2nd for force out → throw to 1st for another out. Pitchers love it!',
  },
  {
    id: 'r14',
    question: 'What does it mean to "tag up"?',
    options: [
      'Touch the base with your hand',
      'Wait on your base until a fly ball is caught, then run',
      'Slide into a base head-first',
      'Run before the pitcher throws',
    ],
    correct: 1,
    explanation: 'Tag up: stay on your base while the fly ball is in the air, then run AFTER the catch. A deep fly ball might let a runner on 3rd score!',
  },
  {
    id: 'r15',
    question: 'When a pitcher throws 4 balls, what happens?',
    options: [
      'The pitcher is removed',
      'The batter gets an extra strike',
      'The batter walks to first base',
      'The inning is over',
    ],
    correct: 2,
    explanation: 'Walk! 4 balls = free trip to first base. Free runs hurt — throw strikes!',
  },
  {
    id: 'r16',
    question: 'What is an "error" in baseball?',
    options: [
      'When a pitcher throws a ball outside the zone',
      'When a batter swings and misses',
      'When a fielder makes a mistake on a play they should have made',
      'When a runner runs the wrong direction',
    ],
    correct: 2,
    explanation: 'An error is a fielding mistake — dropping a throw, bobbling a grounder — that lets a batter or runner reach base when they should have been out.',
  },
  {
    id: 'r17',
    question: 'What does "SS" stand for in baseball?',
    options: ['Second Stop', 'Slow Swinger', 'Slugging Star', 'Shortstop'],
    correct: 3,
    explanation: 'SS = Shortstop! They play between 2nd and 3rd and are usually the team\'s best fielder.',
  },
  {
    id: 'r18',
    question: 'A batted ball rolls into foul territory before passing 1st or 3rd base. What is it?',
    options: [
      'A fair ball — it started in fair territory',
      'A foul ball',
      'Depends on where the fielder picks it up',
      'An automatic double',
    ],
    correct: 1,
    explanation: 'Foul ball! If a batted ball rolls foul before passing 1st or 3rd base, it\'s foul — even if it started fair.',
  },
  {
    id: 'r19',
    question: 'What is a "sacrifice fly"?',
    options: [
      'A fly ball the pitcher throws on purpose',
      'A fly ball that scores a runner even though the batter is called out',
      'When a fielder drops a fly ball on purpose',
      'A pop fly caught in foul territory',
    ],
    correct: 1,
    explanation: 'A sac fly: the batter hits a deep fly ball, the fielder catches it (batter is out), but a runner tags up from 3rd and scores. The batter "sacrificed" for the team!',
  },
  {
    id: 'r20',
    question: 'What is the job of the SHORTSTOP?',
    options: [
      'Catch fly balls in left field',
      'Cover first base on all plays',
      'Field ground balls between 2nd and 3rd base',
      'Back up the pitcher every play',
    ],
    correct: 2,
    explanation: 'Shortstop covers the area between 2nd and 3rd base, fields grounders, and covers 2nd on many plays. Usually the team\'s best all-around fielder!',
  },
  {
    id: 'r21',
    question: 'What is a "triple play"?',
    options: [
      'When a batter hits three times in one at-bat',
      'Three outs on a single play — the rarest play in baseball',
      'When three runners score on one hit',
      'When the pitcher strikes out three batters in a row',
    ],
    correct: 1,
    explanation: 'A triple play is 3 outs on 1 play — incredibly rare and spectacular! Usually needs runners on base with a line drive the fielder catches, then throws quickly for two more outs.',
  },
  {
    id: 'r22',
    question: 'What is a "force play" vs a "tag play"?',
    options: [
      'Force play = runner must run, just touch the base; Tag play = runner has a choice, must tag them',
      'They\'re the same thing',
      'Force play = runner runs home; Tag play = runner runs to 1st',
      'Force play = infield only; Tag play = outfield only',
    ],
    correct: 0,
    explanation: 'Key difference: on a force, the runner HAS to run — just touch the base with the ball. On a tag play, the runner chose to run — you must actually tag them with the ball!',
  },
  // ── 9U Kid Pitch / Open Bases specific ──
  {
    id: 'r23',
    question: 'In "open bases" travel ball, WHEN can a runner take a leadoff?',
    options: [
      'Any time they want, even before the pitch',
      'Only after the ball is hit',
      'After the pitcher releases the ball (or the pitch crosses the plate)',
      'Only on steal attempts',
    ],
    correct: 2,
    explanation: 'In open bases, runners leave the base once the pitcher releases the ball. Leave too early = you can be called out! Coaches teach the timing so runners get a good jump legally.',
  },
  {
    id: 'r24',
    question: 'What is a "dropped third strike" and when can the batter run to first?',
    options: [
      'The catcher drops strike 3 — batter can ALWAYS run',
      'The catcher drops strike 3 — batter can run if 1st base is empty OR there are 2 outs',
      'The catcher drops strike 3 — batter is always out',
      'Only happens with 2 strikes on the batter',
    ],
    correct: 1,
    explanation: 'Dropped third strike: if the catcher doesn\'t catch strike 3 cleanly, the batter can run to 1st IF first base is unoccupied OR it\'s 2 outs. The catcher must throw to 1st to get the batter out!',
  },
  {
    id: 'r25',
    question: 'What is a "balk"?',
    options: [
      'When the pitcher throws the ball too slowly',
      'An illegal motion by the pitcher with runners on base — all runners advance one base',
      'When the pitcher drops the ball before throwing',
      'A pitch that bounces in the dirt before home plate',
    ],
    correct: 1,
    explanation: 'A balk is an illegal move by the pitcher with runners on base. Common balks: not stopping in the "set" position, faking a throw without throwing, or dropping the ball off the rubber. All runners advance one base — free!',
  },
  {
    id: 'r26',
    question: 'What is the "infield fly rule"?',
    options: [
      'Any ball hit in the infield is automatically an out',
      'With runners on 1st & 2nd (or bases loaded) and fewer than 2 outs, a pop-up to the infield is an automatic out',
      'When a fly ball is mishandled in the infield',
      'Only applies when the bases are empty',
    ],
    correct: 1,
    explanation: 'The infield fly rule protects runners. Without it, a fielder could drop a pop-up on purpose to get a cheap double or triple play. The batter is called out immediately so runners don\'t have to risk advancing.',
  },
  {
    id: 'r27',
    question: 'A runner is on 1st base. The pitcher legally throws to 1st base to try to pick off the runner. What is this called?',
    options: [
      'A balk',
      'A wild pitch',
      'A pick-off attempt',
      'A passed ball',
    ],
    correct: 2,
    explanation: 'Pick-off! The pitcher throws to a base to try to catch a runner who\'s leaning too far off. In kid pitch, good pitchers use pick-offs to keep runners honest. Runners must get back to the bag fast!',
  },
  {
    id: 'r28',
    question: 'A runner is on 2nd and tries to steal 3rd. The catcher throws to 3rd. The ball goes into left field. Can the runner score?',
    options: [
      'No — the runner must stay at 3rd on any overthrow during a steal',
      'Yes — any overthrow is a live ball and the runner can try to score',
      'Yes, but only if the coach waves them home',
      'No — all steals are dead balls if there\'s an overthrow',
    ],
    correct: 1,
    explanation: 'Live ball! Under standard rules, if the catcher\'s throw goes into the outfield, it\'s still live and the runner can try to score. (Check your tournament rules — some 9U leagues make overthrows dead to speed up games.) This is why LF ALWAYS backs up 3rd on steal attempts!',
  },
  {
    id: 'r29',
    question: 'With a runner on 1st base, the pitcher MUST do what before delivering the pitch?',
    options: [
      'Throw to 1st base first',
      'Come to a complete STOP in the "set" position before throwing home',
      'Step off the rubber',
      'Nothing special — pitch the same way as with nobody on',
    ],
    correct: 1,
    explanation: 'Most pitchers use the "set" (stretch) position with runners on base, and from the set they MUST come to a complete stop before delivering the pitch. Skip the stop = BALK — all runners advance one base for free! The set position also helps the pitcher watch the runners and attempt pick-offs.',
  },
  {
    id: 'r30',
    question: 'What does "open bases" mean in travel ball?',
    options: [
      'All bases are uncovered — no fielders allowed there',
      'Runners can lead off and steal any base freely',
      'There are extra bases on the field',
      'Runners can only steal on wild pitches',
    ],
    correct: 1,
    explanation: '"Open bases" means runners can lead off and steal any base — just like standard baseball. This is different from some rec leagues where stealing is limited. Be ready: runners will be going!',
  },
  {
    id: 'r31',
    question: 'Runner stealing 2nd base. The catcher throws to 2nd. What does the CENTER FIELDER do?',
    options: [
      'Cover second base',
      'Back up the throw to second base',
      'Run toward home plate',
      'Cover third base',
    ],
    correct: 1,
    explanation: 'CF backs up 2nd on every steal attempt! If the throw gets past the shortstop, CF is there to stop the runner from taking 3rd. Never be caught flat-footed on a steal — center fielders always move!',
  },
  // ── New content ──
  {
    id: 'r32',
    question: 'A pitch hits the batter in the leg while they\'re standing in the batter\'s box. What happens?',
    options: [
      'The batter is out for getting in the way',
      'The batter gets to walk to first base',
      'It\'s just a ball — the at-bat continues',
      'The batter gets to re-hit the pitch',
    ],
    correct: 1,
    explanation: 'Hit by pitch = free base! The ball is dead and the batter trots to first. Any runners only advance if forced. And yes — it still counts even if it wasn\'t a strike zone pitch. Take the base!',
  },
  {
    id: 'r33',
    question: 'The batter has 2 strikes and tries to bunt. The bunt rolls foul. What happens?',
    options: [
      'Just a foul ball — the at-bat continues',
      'The batter gets one more chance',
      'The batter is STRUCK OUT — a foul bunt on strike 3 is a strikeout',
      'The pitch is called a ball',
    ],
    correct: 2,
    explanation: 'Foul bunt with 2 strikes = STRIKEOUT! A normal foul ball can\'t strike you out, but a BUNT that goes foul on strike 3 is an out. This is why bunting with 2 strikes is risky — don\'t do it unless you\'re sure!',
  },
  {
    id: 'r34',
    question: 'In open bases travel ball, a runner on 2nd leaves BEFORE the pitcher releases the ball. What is called?',
    options: [
      'Nothing — runners can leave whenever they want in open bases',
      'The runner is called OUT for leaving early',
      'The batter gets a free ball added to the count',
      'The umpire gives a warning first',
    ],
    correct: 1,
    explanation: 'Leave early = you\'re OUT! In open bases you may leave AFTER the pitcher releases. Go before that and the umpire can call you out immediately. Good base runners time their breaks perfectly — just a hair too early costs an out!',
  },
  {
    id: 'r35',
    question: 'A pitch bounces wildly in the dirt. The catcher dives but can\'t stop it — it was so wild no catcher could block it. What is this called?',
    options: [
      'A passed ball (catcher\'s fault)',
      'A wild pitch (pitcher\'s fault)',
      'A balk',
      'An error on the catcher',
    ],
    correct: 1,
    explanation: 'Wild pitch! When the ball is SO bad no catcher could reasonably stop it, it\'s on the pitcher. A PASSED BALL is when the catcher fails to stop a pitch they should have blocked — that\'s on the catcher. Either way, runners can try to advance!',
  },
  {
    id: 'r36',
    question: 'Wild pitch with a runner on 3rd. The catcher sprints to chase the ball. Who must immediately run to cover home plate?',
    options: [
      'The first baseman',
      'The shortstop',
      'The pitcher',
      'Nobody — home plate covers itself on wild pitches',
    ],
    correct: 2,
    explanation: 'PITCHER covers home! The second the catcher leaves to chase a wild pitch or passed ball, the pitcher sprints to the plate to receive the throw. Nobody there = easy run. This is one of the most forgotten plays in 9U — pitchers must react instantly!',
  },
  {
    id: 'r37',
    question: 'Runner on 1st. The batter hits a ground ball that hits the runner in fair territory before any fielder can touch it. What is called?',
    options: [
      'The runner gets a free base — they were just in the way',
      'The ball is live — play continues normally',
      'The runner is OUT and the batter gets credit for a single',
      'It\'s a do-over — replay the pitch',
    ],
    correct: 2,
    explanation: 'Runner is OUT! If a batted ball hits a runner in fair territory before passing a fielder (other than the pitcher), the runner is out, ball is dead, and batter gets a single. Runners have to watch the ball and get out of its path!',
  },
  {
    id: 'r38',
    question: 'A batter hits a ball that bounces fair in the outfield — then bounces OVER the fence into the stands. What is it?',
    options: [
      'Home run — it went out of the park',
      'Keep running — it\'s a live ball',
      'Ground rule double — batter gets 2nd, runners get 2 bases',
      'Foul ball — it left fair territory',
    ],
    correct: 2,
    explanation: 'Ground rule double! Any ball that bounces INTO the stands (not over on the fly) is a ground rule double. Batter gets 2nd, all runners get 2 bases from where they were when the ball was pitched. It\'s not a home run because it bounced — it didn\'t clear the fence in the air!',
  },
  {
    id: 'r39',
    question: 'In baseball scorekeeping every position has a number. What number is the SHORTSTOP?',
    options: ['3', '4', '5', '6'],
    correct: 3,
    explanation: 'Shortstop = 6! The full list: P=1, C=2, 1B=3, 2B=4, 3B=5, SS=6, LF=7, CF=8, RF=9. A classic "6-4-3" double play means SS → 2B → 1B. Scorekeepers write plays in numbers to be fast — now you can read the scorebook!',
  },
  {
    id: 'r40',
    question: 'In open bases travel ball, can a runner on 3rd base STEAL HOME?',
    options: [
      'No — home plate can never be stolen',
      'Yes — but only on a wild pitch',
      'Yes — after the pitcher releases the ball, the runner can break for home',
      'Yes — but only with 2 outs',
    ],
    correct: 2,
    explanation: 'Steal home is LEGAL in open bases! Once the pitcher releases the ball, the runner on 3rd can break for home. It\'s rare and risky — but it CAN happen. Catchers and pitchers must always watch the runner on 3rd, especially late in close games!',
  },
  {
    id: 'r41',
    question: 'A batter gets a single and runs hard past first base into foul territory. Can they be tagged out?',
    options: [
      'Yes — any time they leave the base they can be tagged',
      'No — you can ALWAYS overrun first base safely',
      'Only if they make a move (turn) toward second base',
      'Only if the first baseman catches them',
    ],
    correct: 2,
    explanation: 'You can overrun 1B safely — but ONLY if you don\'t turn toward 2nd. If the umpire judges you made a move toward second (even slightly), you can be tagged out! Always veer off into foul territory after passing first so there\'s no question.',
  },
  {
    id: 'r42',
    question: 'A fielder throws the ball and it rolls into the dugout — out of play. What happens to the runners?',
    options: [
      'They return to where they were when the throw was made',
      'All runners advance 2 bases from where they were when the ball was thrown',
      'It\'s a dead ball — nobody advances',
      'Only the nearest runner advances',
    ],
    correct: 1,
    explanation: 'Two-base award from the time of the throw! When a thrown ball goes out of play, all runners get 2 bases from where they were when the throw happened. Example: runner on 1st, throw rolls into the dugout → runner gets 3rd. Coaches always count bases on overthrows!',
  },
  {
    id: 'r43',
    question: 'The batter bunts and is thrown out at 1st, but the runner on 1st advances to 2nd. What is this called?',
    options: [
      'A bunt error — the batter should have been safe',
      'A force out at first base',
      'A sacrifice bunt — the batter gave himself up to move the runner',
      'A strikeout — bunts always count as strikes',
    ],
    correct: 2,
    explanation: 'Sacrifice bunt! The batter gave himself up ON PURPOSE to advance the runner. It counts as a plate appearance but NOT an at-bat, so it doesn\'t hurt the batting average. Pure team play — sometimes moving the runner forward is worth more than any hit!',
  },
  {
    id: 'r44',
    question: 'A runner is sprinting to 2nd base. A fielder WITHOUT the ball steps in front of them and blocks the path. What is this called?',
    options: [
      'Interference — the runner ran into the fielder',
      'Obstruction — the fielder\'s fault, runner is awarded the base',
      'Legal — fielders can stand wherever they want',
      'A balk — fielders can\'t block paths',
    ],
    correct: 1,
    explanation: 'Obstruction! A fielder who doesn\'t have the ball cannot block a runner\'s path. The umpire calls obstruction and awards the runner the base they were going to. The opposite is INTERFERENCE — when the offense (batter/runner) gets in the fielder\'s way. Know the difference!',
  },
  {
    id: 'r45',
    question: 'The pitcher is in the windup. The batter steps out and yells "Time!" The umpire says nothing and the pitcher delivers. Is the pitch live?',
    options: [
      'No — the batter can always call time by stepping out',
      'Yes — only the UMPIRE can grant time; the pitch is live',
      'Only if the catcher didn\'t motion for time first',
      'Yes, but the umpire must warn the batter first',
    ],
    correct: 1,
    explanation: 'Only the UMPIRE can grant time! A batter or coach can REQUEST it, but nothing stops until the ump says "TIME!" If they haven\'t called it, the ball is live — and base runners get caught off guard all the time because of this. Never assume time until you hear it!',
  },
  {
    id: 'r46',
    question: 'A ball is hit down the first base line. It\'s in fair territory when it PASSES first base, then rolls into foul territory and stops. Fair or foul?',
    options: [
      'Foul — it ended in foul territory',
      'Fair — where it is when it passes the base (or is touched) determines fair/foul',
      'Whatever the umpire decides on the spot',
      'Depends on which direction the spin carries it',
    ],
    correct: 1,
    explanation: 'FAIR! For balls that travel past 1st or 3rd base, what matters is where the ball IS when a fielder touches it — or where it lands in the outfield. If it passed the bag in fair territory, it\'s fair. Only between home and the bag does a ball rolling foul make it a foul ball!',
  },
  {
    id: 'r47',
    question: 'Runners are on base. A fielder catches a FLY BALL in foul territory near the left field line. Can runners tag up and advance?',
    options: [
      'No — foul balls are always dead, runners cannot advance',
      'Yes — on any legally caught fly ball (fair OR foul), runners can tag up and advance',
      'Only if the ball was in fair territory when caught',
      'Only with 2 outs',
    ],
    correct: 1,
    explanation: 'YES — runners can tag up on a foul fly ball! Any legally caught fly ball, fair or foul, lets runners tag up after the catch. A deep foul fly near the pole can still score a runner from 3rd! Outfielders: know this before waving off a tough foul ball.',
  },
  {
    id: 'r48',
    question: 'What is a GRAND SLAM?',
    options: [
      'A home run with the bases loaded — batter and all 3 runners score (4 runs!)',
      'A home run hit especially far',
      'When a team scores 4 or more runs in one inning',
      'A home run with 2 outs',
    ],
    correct: 0,
    explanation: 'Grand slam = bases LOADED home run! All 3 runners score PLUS the batter = 4 runs on one swing. It\'s the maximum runs you can score on a single play. Pitchers fear it more than anything — never walk the bases loaded!',
  },
  {
    id: 'r49',
    question: 'What does it mean to hit "for the cycle" in a single game?',
    options: [
      'Hit 4 home runs in one game',
      'Hit the same type of hit 4 times in a row',
      'Hit a single, double, triple, AND home run all in one game',
      'Strike out 4 times in one game',
    ],
    correct: 2,
    explanation: 'The cycle = single + double + triple + home run in one game! Order doesn\'t matter. It\'s one of the rarest individual achievements in baseball. The triple is usually the hardest piece — that\'s pure speed and hustle!',
  },
  {
    id: 'r50',
    question: 'What is a "squeeze play"?',
    options: [
      'When fielders trap a runner in a rundown between two bases',
      'When the batter bunts to score a runner from 3rd base',
      'When the catcher squeezes the ball hard on a tag play',
      'A double steal with runners on 1st and 3rd',
    ],
    correct: 1,
    explanation: 'Squeeze play! Runner on 3rd, batter bunts — often as the runner is already breaking for home. Done right, the runner scores before the fielder can throw home. The "safety squeeze" waits to see the bunt; the "suicide squeeze" has the runner going no matter what. Pure excitement!',
  },
  {
    id: 'r51',
    question: 'Home team is losing 3-2 in the last inning. Their batter hits a 2-run homer to win 4-3. What is this called?',
    options: [
      'A come-from-behind win',
      'A walk-off home run',
      'A rally hit',
      'A clutch triple',
    ],
    correct: 1,
    explanation: 'WALK-OFF! Any hit, walk, or error that ends the game with the home team winning in their last at-bat is a walk-off — everyone literally "walks off" the field. The bench mob, the dogpile, the pure joy — walk-offs are the most electric moment in baseball!',
  },
];

// ─── BACKUP SCENARIOS ────────────────────────────────────────────────────────
// 9U Kid Pitch, Open Bases — tap the correct position circle on the diamond.
// NOTE FOR COACH: Review these with your team — especially steal coverage (b16)
// which varies by team. SS covering steal attempts to 2nd is the most common
// default, but some teams use 2B based on batter handedness.

export const BACKUP_SCENARIOS: BackupScenario[] = [
  // ── Outfield backups ──
  {
    id: 'b1',
    label: 'Single to Left Field — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: 'LF',
    question: 'Ball hit to LEFT FIELD! Tap the outfielder who backs up the left fielder.',
    targetZone: 'CF',
    explanation: 'CF backs up LF! Center field sprints over in case the ball gets past the left fielder. Never let a ball roll to the fence unchallenged!',
    ballReachesTarget: false,
  },
  {
    id: 'b2',
    label: 'Single to Center Field — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: 'CF',
    question: 'Ball hit to CENTER FIELD! Tap the outfielder who backs up CF from the left side.',
    targetZone: 'LF',
    explanation: 'LF backs up CF! Left field cheats toward center whenever the ball is hit that direction. Outfielders always back up their neighbors.',
    ballReachesTarget: false,
  },
  {
    id: 'b3',
    label: 'Single to Right Field — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: 'RF',
    question: 'Ball hit to RIGHT FIELD! Tap the outfielder who backs up the right fielder.',
    targetZone: 'CF',
    explanation: 'CF backs up RF! CF is the middle of the outfield and backs up BOTH corners. Center fielders cover the most ground — they\'re always moving!',
    ballReachesTarget: false,
  },
  // ── Infield ground balls ──
  {
    id: 'b4',
    label: 'Ground Ball to Pitcher — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: 'P',
    question: 'Batter hits it back to the PITCHER, bases empty. Tap where the pitcher throws.',
    targetZone: '1B',
    explanation: 'Throw to first! Bases empty = the out is always at 1B. Field it clean, spin, and fire to first base!',
  },
  {
    id: 'b5',
    label: 'Ground Ball to Shortstop — Runner on 1st',
    runners: { first: true, second: false, third: false },
    ballZone: 'SS',
    question: 'Runner on 1st, ground ball to SHORTSTOP! Tap who covers second base for the force out.',
    targetZone: '2B',
    explanation: '2B covers 2nd! When SS fields the ball, 2B races to the bag for the throw. That\'s the force out on the runner from 1st. They swap — whoever doesn\'t field covers 2nd!',
  },
  {
    id: 'b6',
    label: 'Ground Ball to 2nd Base — Runner on 1st',
    runners: { first: true, second: false, third: false },
    ballZone: '2B',
    question: 'Runner on 1st, ground ball to SECOND BASEMAN! Tap who covers second base.',
    targetZone: 'SS',
    explanation: 'SS covers 2nd! When 2B fields the ball, SS runs to cover the bag for the force out. They always swap — whoever fields it, the other covers second!',
  },
  {
    id: 'b7',
    label: 'Ground Ball to 1st Base — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: '1B',
    question: 'Ground ball to the FIRST BASEMAN, bases empty. Tap who must sprint to cover first base.',
    targetZone: 'P',
    explanation: 'Pitcher covers 1B! When 1B fields the ball, the pitcher must SPRINT to first to receive the throw. This happens constantly — pitchers must hustle every single time!',
  },
  {
    id: 'b8',
    label: 'Ground Ball to 3rd Base — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: '3B',
    question: 'Ground ball to THIRD BASE, bases empty. Tap where the 3rd baseman throws.',
    targetZone: '1B',
    explanation: 'Throw to first! Bases empty = always throw to 1B for the out. The 3B has the longest throw in the infield — field it cleanly and make a strong, accurate throw!',
  },
  // ── Cutoff / relay plays ──
  {
    id: 'b9',
    label: 'Single to Left Field — Runner on 1st',
    runners: { first: true, second: false, third: false },
    ballZone: 'LF',
    question: 'Runner on 1st, single to LEFT FIELD! Tap who runs out to be the relay/cutoff.',
    targetZone: 'SS',
    explanation: 'SS is the cutoff on left field throws! Shortstop runs out between LF and the infield to relay the throw. A long throw from LF loses steam — the SS cuts it off and fires a faster, shorter throw to nail the runner!',
  },
  {
    id: 'b10',
    label: 'Single to Right Field — Runner on 1st',
    runners: { first: true, second: false, third: false },
    ballZone: 'RF',
    question: 'Runner on 1st, single to RIGHT FIELD! Tap who runs out to be the relay/cutoff.',
    targetZone: '2B',
    explanation: '2B is the relay on right field throws! On RF balls, 2B goes out as the cutoff while SS stays to cover 2nd base. It\'s the OPPOSITE of left field (where SS is the cutoff)!',
  },
  // ── Catcher at home ──
  {
    id: 'b11',
    label: 'Single to Center Field — Runner on 2nd',
    runners: { first: false, second: true, third: false },
    ballZone: 'CF',
    question: 'Runner on 2nd, single to CF — runner is racing home! Tap who must protect home plate.',
    targetZone: 'C',
    explanation: 'Catcher stays home! The runner on 2nd is trying to score. The catcher must be at home plate, in position, ready to receive the throw and make the tag. Never leave home plate unguarded!',
  },
  // ── Special plays ──
  {
    id: 'b12',
    label: 'Ground Ball to Pitcher — Runner on 3rd',
    runners: { first: false, second: false, third: true },
    ballZone: 'P',
    question: 'Runner on 3rd, ground ball to the PITCHER. Tap where the pitcher must GLANCE before throwing.',
    targetZone: '3B',
    explanation: 'Glance at third first! With open bases, the runner on 3rd might break for home. The pitcher peeks — if they\'re staying put, fire to 1st for the out. If they\'re going home, throw home! Always check the runner!',
    ballReachesTarget: false,
  },
  {
    id: 'b13',
    label: 'Pop-Up Near Home Plate — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: 'C',
    question: 'A pop-up goes straight up near home plate! Tap who calls off everyone and catches it.',
    targetZone: 'C',
    explanation: 'Catcher takes pop-ups near home! The catcher is already there and can read the whole field. They yell "I GOT IT!" to call off the pitcher. Everyone gives way when the catcher calls it!',
  },
  {
    id: 'b14',
    label: 'Fly Ball to Left Field — Runner on 3rd',
    runners: { first: false, second: false, third: true },
    ballZone: 'LF',
    question: 'Runner on 3rd tags up to score on a fly ball to LF! Tap who sets up as the CUTOFF in front of home plate.',
    targetZone: '3B',
    explanation: '3B is the cutoff on LF throws home! Third base sets up between LF and the plate, directly in the throw\'s path. The catcher yells "CUT!" to intercept if the play at home is lost — or "LET IT GO!" if there\'s a chance to nail the runner at the plate!',
  },
  {
    id: 'b15',
    label: 'Ground Ball to 1st Base — Runner on 1st',
    runners: { first: true, second: false, third: false },
    ballZone: '1B',
    question: 'Runner on 1st, ground ball to the FIRST BASEMAN! Tap who must sprint to cover first base.',
    targetZone: 'P',
    explanation: 'Pitcher covers 1B again! Any time 1B fields the ball, the pitcher sprints to the bag. With a runner on 1st, 1B may throw to SS covering 2nd for the force first — then SS fires back to 1st and the pitcher must be there to finish the 3-6-1 double play!',
  },
  // ── Steal situations (9U Open Bases) ──
  {
    id: 'b16',
    label: 'Steal Attempt — Runner Going to 2nd',
    runners: { first: true, second: false, third: false },
    ballZone: 'C',
    question: 'Runner on 1st is STEALING 2nd! Catcher catches and fires. Tap who covers second base.',
    targetZone: 'SS',
    explanation: 'Shortstop covers 2nd on steal attempts! SS has the best angle crossing the bag. (Some teams use 2B based on batter handedness — ask your coach! But SS is the most common default at 9U.)',
  },
  {
    id: 'b17',
    label: 'Steal of 2nd — Center Fielder\'s Job',
    runners: { first: true, second: false, third: false },
    ballZone: 'C',
    question: 'Runner stealing 2nd, catcher fires to the bag. Tap which outfielder backs up the throw.',
    targetZone: 'CF',
    explanation: 'CF backs up 2nd on EVERY steal attempt! If the throw gets past the shortstop, CF is there to stop the runner from taking 3rd. Center fielders must ALWAYS move on steal attempts — never be caught flat-footed!',
    ballReachesTarget: false,
  },
  {
    id: 'b18',
    label: 'Steal of 3rd — Runner on 2nd',
    runners: { first: false, second: true, third: false },
    ballZone: 'C',
    question: 'Runner on 2nd is STEALING 3rd! Catcher fires down the line. Tap who covers third base.',
    targetZone: '3B',
    explanation: '3B covers third! The third baseman stays at the bag to receive the throw and make the tag. If the throw gets away, LF must back up 3B — and a ball rolling to the LF fence can score a run!',
  },
  {
    id: 'b19',
    label: 'Pick-Off at 1st Base',
    runners: { first: true, second: false, third: false },
    ballZone: 'P',
    question: 'Runner on 1st is leading off. Pitcher throws a PICK-OFF to 1st! Tap who covers 2nd in case the runner breaks.',
    targetZone: 'SS',
    explanation: 'SS covers 2nd on a pickoff to 1st! When the pitcher throws to 1B, the 2B cheats toward the play at first — so SS slides over to guard 2nd in case the runner dodges the tag and breaks. If SS doesn\'t cover, 2nd base is wide open!',
  },
  // ── New scenarios ──
  {
    id: 'b20',
    label: 'Wild Pitch — Runner on 3rd Breaks for Home',
    runners: { first: false, second: false, third: true },
    ballZone: 'C',
    question: 'WILD PITCH! Runner on 3rd breaks for home. The catcher sprints to chase the ball. Tap which fielder must cover home plate.',
    targetZone: 'P',
    explanation: 'PITCHER covers home! The instant the catcher leaves to chase a wild pitch or passed ball, the pitcher SPRINTS to the plate to receive the throw. Nobody there = free run. This is one of the most important — and most forgotten — plays at 9U. Pitchers must react immediately every single pitch!',
  },
  {
    id: 'b21',
    label: 'Fly Ball to RF — Runner on 3rd Tags to Score',
    runners: { first: false, second: false, third: true },
    ballZone: 'RF',
    question: 'Runner on 3rd tags up on a fly ball to RIGHT FIELD! Runner racing home. Tap who sets up as the CUTOFF in front of home plate.',
    targetZone: '1B',
    explanation: '1B is the cutoff on RF throws home! First base sets up between RF and the plate in a direct line. The catcher yells "CUT!" to intercept if the play is lost — or "LET IT GO!" if there\'s a chance to nail the runner. Remember: 3B is the cutoff on LF throws home; 1B is the cutoff on RF throws home!',
  },
  {
    id: 'b22',
    label: 'Extra-Base Hit to LF Gap',
    runners: { first: true, second: false, third: false },
    ballZone: 'LF',
    question: 'Ball GAPPED in left field — runners flying! Tap who sprints out toward left field to be the relay man.',
    targetZone: 'SS',
    explanation: 'SS goes out as the relay! On extra-base hits to left field, SS runs out between LF and the infield to cut off the long throw and fire a shorter, faster relay to the base. Without a relay, the long throw from deep LF dies before it gets anywhere. SS and LF must practice this timing!',
  },
  {
    id: 'b23',
    label: 'Extra-Base Hit to RF Gap',
    runners: { first: true, second: false, third: false },
    ballZone: 'RF',
    question: 'Ball BLASTED into the right field gap — runners moving! Tap who sprints out toward right field to be the relay man.',
    targetZone: '2B',
    explanation: '2B goes out as the relay on RF extra-base hits! On balls to right field, 2B runs out toward RF to relay the throw while SS stays to cover 2nd. It\'s the OPPOSITE of left field (where SS is the relay). Know your job based on which side the ball is hit!',
  },
  {
    id: 'b24',
    label: 'Fly Ball to CF — Runner on 3rd Tags to Score',
    runners: { first: false, second: false, third: true },
    ballZone: 'CF',
    question: 'Runner on 3rd tags up on a fly ball to CENTER FIELD! Runner racing home. Tap who sets up as the CUTOFF in front of home plate.',
    targetZone: 'SS',
    explanation: 'SS is the cutoff on CF throws home! Shortstop sets up in a direct line between CF and the plate. The catcher yells "CUT!" to intercept if needed or "LET IT GO!" for the play at the plate. For right-center balls, some teams use 2B instead — ask your coach which your team prefers!',
  },
  {
    id: 'b25',
    label: 'Bunt — 1B Charges, Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: '1B',
    question: 'Batter drops a BUNT down the first base line! The 1B charges in to field it. Tap who must sprint to cover first base.',
    targetZone: 'P',
    explanation: 'Pitcher covers 1B on every bunt! When 1B charges a bunt, they can\'t get back to the bag in time. The pitcher MUST sprint to first to receive the throw. This happens constantly in bunt situations — pitchers who don\'t hustle give away free outs. Field the bunt, stay calm, flip to the pitcher at the bag!',
  },
  {
    id: 'b26',
    label: 'Bases Loaded — Ground Ball to 3rd',
    runners: { first: true, second: true, third: true },
    ballZone: '3B',
    question: 'BASES LOADED! Ground ball to 3rd base. Tap where 3B should throw for the force out on the LEAD RUNNER (the one coming from 3rd).',
    targetZone: 'C',
    explanation: 'Throw home! With bases loaded, EVERY runner is forced to advance — including the runner at 3rd who is forced to score. 3B throws to the catcher at home for the force-out (no tag needed, just touch the plate). Then the catcher can try for the 1B double play. Never forget — bases loaded means there\'s a force everywhere, including home!',
  },
  {
    id: 'b27',
    label: 'Ground Ball to SS — Runner on 2nd Only',
    runners: { first: false, second: true, third: false },
    ballZone: 'SS',
    question: 'Runner on 2nd ONLY (no runner on 1st), ground ball to SHORTSTOP. No force at 3rd. Tap where SS should throw for the SURE out.',
    targetZone: '1B',
    explanation: 'Throw to 1B for the sure out! There\'s no force at 3rd — the runner on 2nd doesn\'t HAVE to go because nobody is behind them forcing them. Going for a tag at 3rd is risky. SS takes the sure out at 1B. The runner might reach 3rd, but one certain out beats a risky tag attempt!',
  },
  {
    id: 'b28',
    label: 'Ground Ball to 2B — Runner on 2nd Only',
    runners: { first: false, second: true, third: false },
    ballZone: '2B',
    question: 'Runner on 2nd only, ground ball to SECOND BASEMAN. Tap where 2B should throw for the sure out.',
    targetZone: '1B',
    explanation: 'Throw to 1B! With only a runner on 2nd (no runner on 1st creating a force), there\'s no force at any base — the runner isn\'t forced to advance. 2B fields it and fires to 1B for the easy out. The runner will advance to 3rd, but you still got the out. One sure out is always better than a gamble!',
  },
  {
    id: 'b29',
    label: 'Pick-Off at 2nd Base',
    runners: { first: false, second: true, third: false },
    ballZone: 'P',
    question: 'Runner on 2nd is taking a big lead! Pitcher spins and fires a PICK-OFF to 2nd base. Tap who must cover the bag.',
    targetZone: 'SS',
    explanation: 'SS covers 2nd on the pick-off! When the pitcher spins to throw to 2nd, SS breaks for the bag to receive it. This is a TIMING PLAY — pitcher and SS must practice it together in advance or it falls apart. Some teams also use 2B for this. Either way, someone must be at 2nd before the throw arrives!',
  },
  {
    id: 'b30',
    label: 'Infield Popup — Mound/2B Area',
    runners: { first: false, second: false, third: false },
    ballZone: 'P',
    question: 'Popup drifting over the mound toward second base! Pitcher, SS, and 2B are all nearby. Tap who should call everyone off and catch it.',
    targetZone: 'SS',
    explanation: 'Shortstop! SS is the captain of the infield. On pop-ups in the middle of the infield, SS calls for the ball and waves off the pitcher and 2B. Coming in toward the ball is always easier than backing up. When SS yells "I GOT IT!" — everyone else clears out immediately!',
  },
  {
    id: 'b31',
    label: 'Runners on 1st and 2nd — Ground Ball to SS',
    runners: { first: true, second: true, third: false },
    ballZone: 'SS',
    question: 'Runners on 1st AND 2nd! Ground ball to SHORTSTOP. Tap where SS should throw for the force out on the LEAD RUNNER.',
    targetZone: '3B',
    explanation: 'Throw to 3rd for the lead runner! With runners on 1st and 2nd, the runner at 2nd is FORCED to go to 3rd. SS fires to 3B for the force-out (no tag needed), then 3B fires to 1B to try for the double play. Always get the lead runner first — it takes the pressure off the inning!',
  },
  {
    id: 'b32',
    label: 'Single to LF — Runner on 2nd, Throw to 3rd',
    runners: { first: false, second: true, third: false },
    ballZone: 'LF',
    question: 'Runner on 2nd, single to LEFT FIELD — runner racing to 3rd! LF fires to 3rd base. Tap who backs up that throw.',
    targetZone: 'P',
    explanation: 'The PITCHER backs up 3rd! When LF fires to 3rd, the pitcher sprints down the left side and sets up behind 3rd base. If the throw gets past 3B, the pitcher is there to stop the runner from scoring. CF is too far away to back up 3rd in time. Pitchers must read where throws are going and sprint to back up — every time!',
    ballReachesTarget: false,
  },
  {
    id: 'b33',
    label: 'Ground Ball to 3B — Runner on 2nd Only',
    runners: { first: false, second: true, third: false },
    ballZone: '3B',
    question: 'Runner on 2nd only, ground ball to THIRD BASE! Runner on 2nd wasn\'t forced — where should 3B throw for the sure out?',
    targetZone: '1B',
    explanation: 'Throw to 1B for the sure out! No runner on 1st means the runner at 2nd is NOT forced to go to 3rd. 3B fields it, peeks at the runner — if they\'re not a dead duck at 3rd, fire to 1B for the certain out. Don\'t risk a tag play when 1B is a guaranteed out. Simple baseball: take what the defense gives you!',
  },
  {
    id: 'b34',
    label: 'Bases Loaded — Ground Ball to Pitcher',
    runners: { first: true, second: true, third: true },
    ballZone: 'P',
    question: 'BASES LOADED! Pitcher fields a ground ball. Tap where they should throw for the force out on the lead runner.',
    targetZone: 'C',
    explanation: 'Throw HOME! With bases loaded, every runner is forced to advance — including the runner on 3rd forced to score. Pitcher fires to the catcher at home (force out, no tag), then catcher fires to 1B for the double play. This is the highest-pressure play in 9U — field it clean, stay calm, and fire home. Don\'t panic!',
  },
  {
    id: 'b35',
    label: 'Ground Ball to Shortstop — Bases Empty',
    runners: { first: false, second: false, third: false },
    ballZone: 'SS',
    question: 'Bases empty, ground ball to SHORTSTOP! Tap who backs up first base on the throw.',
    targetZone: 'RF',
    explanation: 'RF backs up first base! Anytime there\'s a throw to first from the infield, the right fielder should already be moving to back it up in case of an overthrow. Same idea as LF backing up third — somebody\'s always got the throw covered!',
    ballReachesTarget: false,
  },
  {
    id: 'b36',
    label: 'Pick-Off at 1st Base — Corner Coverage',
    runners: { first: true, second: false, third: false },
    ballZone: 'P',
    question: 'Runner on 1st takes a big lead. Pitcher throws a PICK-OFF to 1st! Tap who backs up 1B in case the throw gets away.',
    targetZone: 'RF',
    explanation: 'RF backs up 1B on pickoffs too! If the throw sails past the first baseman, the right fielder is the only one back there to stop it from rolling to the fence. Stay alert and keep moving every time the pitcher throws over!',
    ballReachesTarget: false,
  },
];
