// GENERATED by scripts/gen-scenario-catalog.mjs — DO NOT EDIT BY HAND.
// Client-safe projection of BACKUP_SCENARIOS: non-answer fields only.
// Answer fields (question, targetZone, explanation) live server-only in gameData.ts.
import type { ScenarioCategory, FieldZone, ScenarioCatalogEntry } from "./scenarioTypes.ts";

export const SCENARIO_CATALOG: ScenarioCatalogEntry[] = [
  {
    "id": "b1",
    "label": "Single to Left Field — Bases Empty",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b2",
    "label": "Single to Center Field — Bases Empty",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "CF",
    "ballReachesTarget": false
  },
  {
    "id": "b3",
    "label": "Single to Right Field — Bases Empty",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "RF",
    "ballReachesTarget": false
  },
  {
    "id": "b4",
    "label": "Ground Ball to Pitcher — Bases Empty",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b5",
    "label": "Ground Ball to Shortstop — Runner on 1st",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "SS"
  },
  {
    "id": "b6",
    "label": "Ground Ball to 2nd Base — Runner on 1st",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "2B"
  },
  {
    "id": "b7",
    "label": "Ground Ball to 1st Base — Bases Empty",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B"
  },
  {
    "id": "b8",
    "label": "Ground Ball to 3rd Base — Bases Empty",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "3B"
  },
  {
    "id": "b9",
    "label": "Single to Left Field — Runner on 1st",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "LF"
  },
  {
    "id": "b10",
    "label": "Single to Right Field — Runner on 1st",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b11",
    "label": "Single to Center Field — Runner on 2nd",
    "category": "cover",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "CF"
  },
  {
    "id": "b12",
    "label": "Ground Ball to Pitcher — Runner on 3rd",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "P",
    "ballReachesTarget": false
  },
  {
    "id": "b13",
    "label": "Pop-Up Near Home Plate — Bases Empty",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b14",
    "label": "Fly Ball to Left Field — Runner on 3rd",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "LF"
  },
  {
    "id": "b15",
    "label": "Ground Ball to 1st Base — Runner on 1st",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "1B"
  },
  {
    "id": "b16",
    "label": "Steal Attempt — Runner Going to 2nd",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b17",
    "label": "Steal of 2nd — Center Fielder's Job",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "C",
    "ballReachesTarget": false
  },
  {
    "id": "b18",
    "label": "Steal of 3rd — Runner on 2nd",
    "category": "cover",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b19",
    "label": "Pick-Off at 1st Base",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b20",
    "label": "Wild Pitch — Runner on 3rd Breaks for Home",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "C"
  },
  {
    "id": "b21",
    "label": "Fly Ball to RF — Runner on 3rd Tags to Score",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "RF"
  },
  {
    "id": "b22",
    "label": "Extra-Base Hit to LF Gap",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "LF"
  },
  {
    "id": "b23",
    "label": "Extra-Base Hit to RF Gap",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b24",
    "label": "Fly Ball to CF — Runner on 3rd Tags to Score",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "CF"
  },
  {
    "id": "b25",
    "label": "Bunt — 1B Charges, Bases Empty",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B"
  },
  {
    "id": "b26",
    "label": "Bases Loaded — Ground Ball to 3rd",
    "category": "relay",
    "runners": {
      "first": true,
      "second": true,
      "third": true
    },
    "ballZone": "3B"
  },
  {
    "id": "b27",
    "label": "Ground Ball to SS — Runner on 2nd Only",
    "category": "relay",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "SS"
  },
  {
    "id": "b28",
    "label": "Ground Ball to 2B — Runner on 2nd Only",
    "category": "relay",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "2B"
  },
  {
    "id": "b29",
    "label": "Pick-Off at 2nd Base",
    "category": "cover",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b30",
    "label": "Infield Popup — Mound/2B Area",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b31",
    "label": "Runners on 1st and 2nd — Ground Ball to SS",
    "category": "relay",
    "runners": {
      "first": true,
      "second": true,
      "third": false
    },
    "ballZone": "SS"
  },
  {
    "id": "b32",
    "label": "Single to LF — Runner on 2nd, Throw to 3rd",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b33",
    "label": "Ground Ball to 3B — Runner on 2nd Only",
    "category": "relay",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "3B"
  },
  {
    "id": "b34",
    "label": "Bases Loaded — Ground Ball to Pitcher",
    "category": "relay",
    "runners": {
      "first": true,
      "second": true,
      "third": true
    },
    "ballZone": "P"
  },
  {
    "id": "b35",
    "label": "Ground Ball to Shortstop — Bases Empty",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "SS",
    "ballReachesTarget": false
  },
  {
    "id": "b36",
    "label": "Pick-Off at 1st Base — Corner Coverage",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "P",
    "ballReachesTarget": false
  },
  {
    "id": "b37",
    "label": "Hard Grounder to 3rd — Bases Empty",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "3B"
  },
  {
    "id": "b38",
    "label": "Hard Grounder to Shortstop — Bases Empty",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "SS"
  },
  {
    "id": "b39",
    "label": "Hard Grounder to 2nd Base — Bases Empty",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "2B"
  },
  {
    "id": "b40",
    "label": "Hard Grounder to 1st Base — Bases Empty",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B"
  },
  {
    "id": "b41",
    "label": "Comebacker to the Pitcher — Bases Empty",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b42",
    "label": "Steal of 2nd — Left-Handed Batter at the Plate",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b43",
    "label": "Bunt — 3rd Baseman Charges, Runner on 1st",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "3B",
    "ballReachesTarget": false
  },
  {
    "id": "b44",
    "label": "Bunt — Pitcher Fields It, 1st Baseman Charged",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b45",
    "label": "Fly Ball to RF — Runner Tags from 1st",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b46",
    "label": "Fly Ball to LF — Runner Tags from 2nd",
    "category": "cover",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "LF"
  },
  {
    "id": "b47",
    "label": "Rundown Between 1st and 2nd",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "1B"
  },
  {
    "id": "b48",
    "label": "Rundown Between 3rd and Home",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "C",
    "ballReachesTarget": false
  },
  {
    "id": "b49",
    "label": "Base Hit to RF — Who Stays at 2nd?",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF",
    "ballReachesTarget": false
  },
  {
    "id": "b50",
    "label": "Base Hit to LF — Who Stays at 2nd?",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b51",
    "label": "Foul Pop-Up Near the 1st Base Dugout",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b52",
    "label": "Foul Pop-Up Down the 3rd Base Line",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b53",
    "label": "Shallow Pop-Up Behind the Shortstop",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "SS"
  },
  {
    "id": "b54",
    "label": "Fly Ball Splitting Left-Center",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "LF"
  },
  {
    "id": "b55",
    "label": "Runners on 1st and 2nd — Ground Ball to 1st",
    "category": "cover",
    "runners": {
      "first": true,
      "second": true,
      "third": false
    },
    "ballZone": "1B"
  },
  {
    "id": "b56",
    "label": "Runner on 2nd Breaks — 3rd Baseman Charging",
    "category": "cover",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "3B"
  },
  {
    "id": "b57",
    "label": "Bunt with a Runner on 3rd — Catcher Fields It",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "C"
  },
  {
    "id": "b58",
    "label": "Runner on 3rd Breaks for Home on the Pitch",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "P"
  },
  {
    "id": "b59",
    "label": "Runner on 1st — Ground Ball to 3rd Base",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "3B"
  },
  {
    "id": "b60",
    "label": "Bases Loaded — Ground Ball to 2nd Base",
    "category": "cover",
    "runners": {
      "first": true,
      "second": true,
      "third": true
    },
    "ballZone": "2B"
  },
  {
    "id": "b61",
    "label": "Shallow Fly to Right — Who Calls It?",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "2B"
  },
  {
    "id": "b62",
    "label": "Comebacker with a Runner on 1st",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b63",
    "label": "Catcher Backs Up First Base",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "3B",
    "ballReachesTarget": false
  },
  {
    "id": "b64",
    "label": "Steal of 3rd — Outfield Backup",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "C",
    "ballReachesTarget": false
  },
  {
    "id": "b65",
    "label": "Throw to 2nd from Left Field",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b66",
    "label": "Single to Center — Runner on 2nd Scoring",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "CF",
    "ballReachesTarget": false
  },
  {
    "id": "b67",
    "label": "Double to Right — Runner Heading to 3rd",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF",
    "ballReachesTarget": false
  },
  {
    "id": "b68",
    "label": "Fly Ball Splitting Right-Center",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "CF",
    "ballReachesTarget": false
  },
  {
    "id": "b69",
    "label": "Dropped Third Strike — Throw to First",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "C",
    "ballReachesTarget": false
  },
  {
    "id": "b70",
    "label": "Throw Home from Left Field",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b71",
    "label": "Ground Ball to 2nd — Throw Across",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "2B",
    "ballReachesTarget": false
  },
  {
    "id": "b72",
    "label": "Bunt — Flip to the Pitcher Covering First",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B",
    "ballReachesTarget": false
  },
  {
    "id": "b73",
    "label": "Pickoff at 2nd — Outfield Backup",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "P",
    "ballReachesTarget": false
  },
  {
    "id": "b74",
    "label": "Pickoff at 3rd — Outfield Backup",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "P",
    "ballReachesTarget": false
  },
  {
    "id": "b75",
    "label": "Pop-Up Behind First Base",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B",
    "ballReachesTarget": false
  },
  {
    "id": "b76",
    "label": "Pop-Up Behind Third Base",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "3B",
    "ballReachesTarget": false
  },
  {
    "id": "b77",
    "label": "Steal of 2nd — Infield Backup",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "C",
    "ballReachesTarget": false
  },
  {
    "id": "b78",
    "label": "Ground Ball to the Pitcher — Outfield Backup",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "P",
    "ballReachesTarget": false
  },
  {
    "id": "b79",
    "label": "Single to Left — Runner on 2nd Scoring, Corner Backup",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b80",
    "label": "Deep Fly to Center — Corner Backup",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "CF",
    "ballReachesTarget": false
  },
  {
    "id": "b81",
    "label": "Bases Loaded — Throw Home, Who Backs Up?",
    "category": "backup",
    "runners": {
      "first": true,
      "second": true,
      "third": true
    },
    "ballZone": "SS",
    "ballReachesTarget": false
  },
  {
    "id": "b82",
    "label": "Runner on 1st — Throw to 2nd from the Right Side",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF",
    "ballReachesTarget": false
  },
  {
    "id": "b83",
    "label": "Squeeze Bunt — Pitcher Throws Home",
    "category": "backup",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "P",
    "ballReachesTarget": false
  },
  {
    "id": "b84",
    "label": "Catcher Backs Up First — Runner on 2nd?",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "SS",
    "ballReachesTarget": false
  },
  {
    "id": "b85",
    "label": "Relay from Deep Left — Backing Up the Relay Man",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b86",
    "label": "Runners on 1st and 3rd — Turn Two",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": true
    },
    "ballZone": "SS"
  },
  {
    "id": "b87",
    "label": "Runner on 3rd — Infield In, Ball to 3rd",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "3B"
  },
  {
    "id": "b88",
    "label": "Runner on 3rd — Two Outs, Ball to Short",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "SS"
  },
  {
    "id": "b89",
    "label": "Bases Loaded — One Out, Ball to Short",
    "category": "relay",
    "runners": {
      "first": true,
      "second": true,
      "third": true
    },
    "ballZone": "SS"
  },
  {
    "id": "b90",
    "label": "Single to Center — Runner Going First to Third",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "CF"
  },
  {
    "id": "b91",
    "label": "Base Hit to Right — Runner Scoring from 2nd",
    "category": "relay",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b92",
    "label": "Long Single to Center — No Play at Third",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "CF"
  },
  {
    "id": "b93",
    "label": "Runner on 1st — Ground Ball to First Base",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "1B"
  },
  {
    "id": "b94",
    "label": "Extra-Base Hit to Left-Center",
    "category": "relay",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "CF"
  },
  {
    "id": "b95",
    "label": "Fly Ball to Right — Runner Left Early",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b96",
    "label": "Sac Fly to Left — No Chance at Home",
    "category": "relay",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "LF"
  },
  {
    "id": "b97",
    "label": "Runner on 2nd Freezes — Ball to the Pitcher",
    "category": "relay",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b98",
    "label": "Runners on 1st and 3rd — Ground Ball to 3rd",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": true
    },
    "ballZone": "3B"
  },
  {
    "id": "b99",
    "label": "Bunt with a Runner on 1st — Pitcher Fields It",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "P"
  },
  {
    "id": "b100",
    "label": "Ball Off the Fence in Right — Relay Man",
    "category": "relay",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b101",
    "label": "Overthrow at First — Who Chases It?",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B",
    "ballReachesTarget": false
  },
  {
    "id": "b102",
    "label": "Overthrow at First — Batter Goes to 2nd",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b103",
    "label": "Steal Throw into Center Field",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "C",
    "ballReachesTarget": false
  },
  {
    "id": "b104",
    "label": "Steal Throw Gets Away — Runner Goes to 3rd",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "CF"
  },
  {
    "id": "b105",
    "label": "Passed Ball — Runner on 1st Takes Off",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b106",
    "label": "Wild Pitch — Runner on 2nd Advances",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b107",
    "label": "Ball Through the Shortstop — Runner on 1st",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "LF"
  },
  {
    "id": "b108",
    "label": "Overthrow at Third — Ball in the Corner",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "3B",
    "ballReachesTarget": false
  },
  {
    "id": "b109",
    "label": "Ball in the Left Corner — Runner Heading Home",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "LF",
    "ballReachesTarget": false
  },
  {
    "id": "b110",
    "label": "Pickoff Throw Sails at First Base",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b111",
    "label": "Throw Pulls the First Baseman Off the Bag",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B",
    "ballReachesTarget": false
  },
  {
    "id": "b112",
    "label": "Dropped Third Strike — Two Outs",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "C"
  },
  {
    "id": "b113",
    "label": "Second Baseman Bobbles It — Runner on 1st",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "2B"
  },
  {
    "id": "b114",
    "label": "Third Baseman Bobbles a Bunt",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "3B"
  },
  {
    "id": "b115",
    "label": "Fly Ball Dropped in Right Field",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b116",
    "label": "First and Third — Steal Throw Gets Away",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": true
    },
    "ballZone": "CF"
  },
  {
    "id": "b117",
    "label": "Bunt Flip Gets Away Down the Line",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "1B",
    "ballReachesTarget": false
  },
  {
    "id": "b118",
    "label": "Overthrow at Third — Runner Scoring",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "LF"
  },
  {
    "id": "b119",
    "label": "Pickoff Gets Away — Runner Trying for Third",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b120",
    "label": "Ball Through the Legs at Second Base",
    "category": "miss_recovery",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "2B",
    "ballReachesTarget": false
  },
  {
    "id": "b121",
    "label": "Catcher Chases a Wild Pitch — Bases Loaded",
    "category": "miss_recovery",
    "runners": {
      "first": true,
      "second": true,
      "third": true
    },
    "ballZone": "C"
  },
  {
    "id": "b122",
    "label": "Deep Fly to Center — Runner Tags from 2nd",
    "category": "cover",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "CF"
  },
  {
    "id": "b123",
    "label": "Base Hit to Center — Who Stays at 2nd?",
    "category": "cover",
    "runners": {
      "first": true,
      "second": false,
      "third": false
    },
    "ballZone": "CF",
    "ballReachesTarget": false
  },
  {
    "id": "b124",
    "label": "Fly Ball Between Right and Center",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": false
    },
    "ballZone": "RF"
  },
  {
    "id": "b125",
    "label": "Fly Ball to Right — Runner Tags from 3rd",
    "category": "cover",
    "runners": {
      "first": false,
      "second": false,
      "third": true
    },
    "ballZone": "RF"
  },
  {
    "id": "b126",
    "label": "Squeeze Play — 3rd Baseman Throws Home",
    "category": "backup",
    "runners": {
      "first": true,
      "second": false,
      "third": true
    },
    "ballZone": "3B",
    "ballReachesTarget": false
  },
  {
    "id": "b127",
    "label": "Pickoff at 2nd — Guarding Third",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "P",
    "ballReachesTarget": false
  },
  {
    "id": "b128",
    "label": "Ground Ball to 1st — Runner on 2nd",
    "category": "backup",
    "runners": {
      "first": false,
      "second": true,
      "third": false
    },
    "ballZone": "1B",
    "ballReachesTarget": false
  }
];

export const SCENARIO_CATALOG_BY_ID: Record<string, ScenarioCatalogEntry> =
  Object.fromEntries(SCENARIO_CATALOG.map((s) => [s.id, s]));

// Per-position bundle summaries (AGGREGATES ONLY — no scenarioId lists, so no
// targetZone can be recovered). Derived from ballZone + targetZone at
// generation time.
export type BundleSummary = {
  scenarioCount: number;
  categoryCounts: Record<ScenarioCategory, number>;
};
export const BUNDLE_SUMMARIES: Partial<Record<FieldZone, BundleSummary>> =
  {
  "P": {
    "scenarioCount": 31,
    "categoryCounts": {
      "cover": 11,
      "backup": 11,
      "relay": 5,
      "miss_recovery": 4
    }
  },
  "C": {
    "scenarioCount": 28,
    "categoryCounts": {
      "cover": 11,
      "backup": 7,
      "relay": 3,
      "miss_recovery": 7
    }
  },
  "1B": {
    "scenarioCount": 29,
    "categoryCounts": {
      "cover": 6,
      "backup": 4,
      "relay": 12,
      "miss_recovery": 7
    }
  },
  "2B": {
    "scenarioCount": 26,
    "categoryCounts": {
      "cover": 9,
      "backup": 4,
      "relay": 8,
      "miss_recovery": 5
    }
  },
  "3B": {
    "scenarioCount": 26,
    "categoryCounts": {
      "cover": 7,
      "backup": 4,
      "relay": 9,
      "miss_recovery": 6
    }
  },
  "SS": {
    "scenarioCount": 36,
    "categoryCounts": {
      "cover": 15,
      "backup": 4,
      "relay": 11,
      "miss_recovery": 6
    }
  },
  "LF": {
    "scenarioCount": 24,
    "categoryCounts": {
      "cover": 4,
      "backup": 11,
      "relay": 4,
      "miss_recovery": 5
    }
  },
  "CF": {
    "scenarioCount": 25,
    "categoryCounts": {
      "cover": 5,
      "backup": 9,
      "relay": 4,
      "miss_recovery": 7
    }
  },
  "RF": {
    "scenarioCount": 30,
    "categoryCounts": {
      "cover": 5,
      "backup": 12,
      "relay": 6,
      "miss_recovery": 7
    }
  }
};
